### ISSUE TITLE
Using with a Browserify based build

### ISSUE THREAD

**Issue by dolfelt** [ArthurClemens/Polythene#10]
I have been wrestling with getting this to work in browserify using Babel. I've added a few plugins to get the paths mapped correctly, but I'm stuck on how to get the CSS to load because of that darn `!` mark at the end, which is specific to the es6-module-loader that systemjs is based on.

Anyone have any thoughts?

**Comment by ArthurClemens** [comment]
As long as the code uses SystemJS plugin syntax, it won't work with other builders. My solution will be to replace all CSS files with j2c, but that is a fair amount of work.

**Comment by ArthurClemens** [comment]
All CSS styles in polythene-theme have been replaced with JS ones. I still need to to the examples and a new solution for the the SVGs.

**Comment by ArthurClemens** [comment]
It now works both with Browserify and with SystemJS. The (now separate) Polythene-examples repo includes a build script for Browserify and can be run with SystemJS from the src directory.

**Comment by dolfelt** [comment]
This is awesome. Thanks! I've already started a project with the updates. :+1:
