### ISSUE TITLE
Polythene not working with node.js

### ISSUE THREAD

**Issue by JoyKrishnaMondal** [ArthurClemens/Polythene#11]
You have not provided an entry point in your package.json. 

I am having difficulty compiling polythene for use with browserify. 

Would you provide some help to make polythene work with node.js with require ?

**Comment by ArthurClemens** [comment]
[The examples repo](https://github.com/ArthurClemens/Polythene-examples) is an app built with browserify and uses [this build script](https://github.com/ArthurClemens/Polythene-examples/blob/master/src/scripts/build.js). Let me know if you have any troubles.
