### ISSUE TITLE
Form components?

### ISSUE THREAD

**Issue by sanchezandoni** [ArthurClemens/Polythene#12]
Great components!
my congrats!
and thanks for making them abailable for the comunity!

some form elements such as inputs, checkboxes, radio buttons, etc. would be great...

**Comment by ArthurClemens** [comment]
Coming up in the next release, within days.

**Comment by ArthurClemens** [comment]
Released with 0.2

**Comment by xhh** [comment]
Looking forward to the Data table and Tooltip components.
Great work!
(wish I have enough CSS skills to contribute :-)
