### ISSUE TITLE
use mouse to start search in Search component

### ISSUE THREAD

**Issue by futurist** [ArthurClemens/Polythene#13]
can it be search with a click after type text in search box?

I've tried when type text the left icon is `Back` and right icon is `Clear`, no button to start search using mouse.

**Comment by ArthurClemens** [comment]
In [the Material Design specs on Search](https://www.google.com/design/spec/patterns/search.html#search-in-app-search) no search button is mentioned. However as documented on http://polythene.js.org/#/search, you can add your own icon buttons and deviate as you like.
