### ISSUE TITLE
Transpiled modules should not be uglified

### ISSUE THREAD

**Issue by veloce** [ArthurClemens/Polythene#17]
Because it prevents quick debugging and source inspection. Also, since they are modules, they are part of a build system that can already perform the uglify step for the whole bundle (if one wants it).

Thus, uglify is only needed for the standalone distribution of Polythene in my opinion.

**Comment by ArthurClemens** [comment]
That is true when using a bundler like Browserify, but I would like to find a solution that can be used with SystemJS too.

**Comment by veloce** [comment]
Ah ok I understand. I guess there is no easy solution to match with all module systems.

**Comment by ArthurClemens** [comment]
A source map per module might help. I need to investigate this.

**Comment by HendrikRoth** [comment]
```js
'use strict';

const watch = require('transpile-watch');

watch({
    persistent: !(process.argv[2] === 'once'),
    what: process.argv[3],
    ignore: (process.argv[4] && process.argv[4] !== 'null') ? process.argv[4] : null,
    extension: '.es6',
    createOutPath: (inPath) => {
        return inPath.replace(/.es6$/, '.js');
    },
    transform: (inPath, outPath) => {
        const sourceMapPath = `${inPath}.map`;
        return [
            `babel ${inPath} |`,

            `exorcist ${sourceMapPath} > ${outPath} ;`,

            `mithril-objectify ${outPath} ${outPath} ;`,

            'uglifyjs -p relative --source-map-root /',
            `--in-source-map ${sourceMapPath} --source-map ${sourceMapPath}`,
            `--screw-ie8 -c -m sort -r \'require,exports\' -o ${outPath} ${outPath}`
        ].join(' ');
    }
});
```
But not perfect at the moment.

**Comment by ArthurClemens** [comment]
@HendrikRoth 

> But not perfect at the moment.

What would you like to improve?

**Comment by HendrikRoth** [comment]
Using mithril-objectify the source map is broken. During development you should not use it.

**Comment by ArthurClemens** [comment]
Working on it, but encountered a problem: https://github.com/mishoo/UglifyJS2/issues/1020

**Comment by ArthurClemens** [comment]
I have added source maps to all files. Using SystemJS this works pretty ok: Chrome dev tools point (mostly) to the right es6 code. I need to investigate a bit more on setting up the right Browserify build script to keep the es6 references, but that is beyond the scope of Polythene itself.
