### ISSUE TITLE
Menu inside Header Panel toolbar click not working

### ISSUE THREAD

**Issue by faandi** [ArthurClemens/Polythene#19]
Hi,

I have some strange issues with a menu inside a header panel's toolbar:

- menu list tile click event does not fire if the tile is over the header panel's content
- the menu background is transparent

Screenshot:
![menu inside header panel](https://cloud.githubusercontent.com/assets/2489786/15078435/80285bd4-13b3-11e6-8a7b-ceb8df133aeb.png)

I have modified the "Example with condensing header" jsfiddle to show the issues:
https://jsfiddle.net/ns2cfsjq/1/

**Comment by faandi** [comment]
Uh, i have found a solution for this issue by simply moving the menu component outside the toolbar like this:

```
return m('.app', [
        m.component(headerPanel, {
             .....
        }),
       m.component(menu, {
            .....
        })
]);
```

jsFiddle:
https://jsfiddle.net/yunuwa3n/2/

**Comment by ArthurClemens** [comment]
The workaround is no longer needed. See for instance the right menu button at http://arthurclemens.github.io/Polythene-examples/index.html#/header-panel/kitchensink, where the menu component is placed in the top bar: https://github.com/ArthurClemens/Polythene-examples/blob/master/src/app/header-panel/demos/common.es6#L44
