### ISSUE TITLE
Body class is not removed when dialog.hide is resolved

### ISSUE THREAD

**Issue by rzetterberg** [ArthurClemens/polythene#21]
## Description

When using the `dialog` component with backdrop set to `true` and doing some
action on resolve of `dialog.hide` the body still has the class
`pe-dialog--open` when the promise is resolved.

I encountered this problem when I was using mithrils routing system to redirect
to another route inside the resolve callback of `dialog.hide().then(...`. Since
the body class removal seemed to happen after the resolve it would never happen
since the call to `m.route(myurl)` would cancel everything happening after it.

Please see provided jsfiddle for a recreation of the problem: https://jsfiddle.net/7ysudkjj/
### Browsers
- Chromium 49 (Linux)
- Firefox 45 (Linux)
### Library version
- 0.2.28 (via npm)
- master 9780575 (via rawgit standalone)
## Workaround

A quick workaround was to remove the class manually. Since I was not using
any other classes on the body I could simply do:

``` javascript
dialog.hide().then(() => {
  document.body.setAttribute('class', '');

  m.route(myurl);
});
```

**Comment by ArthurClemens** [comment]
The reason is that `dialog.hide()` is the command to start hiding the dialog, which initiates a hide transition. Only after the transition has been completed and no other dialogs need to be shown, the class `pe-dialog--open` is removed.

A dependency on the existence of that class seems like a code smell to me. Your workaround is harmless if you are sure that no other dialogs will be shown.

**Comment by rzetterberg** [comment]
@ArthurClemens thanks for the reply!

Maybe I did a poor job at explaining the problem, sorry for that.

> Only after the transition has been completed and no other dialogs need to be shown, the class pe-dialog--open is removed.

Alright, I looked at the code and I think I understand what is happening now. The code that checks if the body class should be removed is run independently in the multiple view function.

> A dependency on the existence of that class seems like a code smell to me. Your workaround is harmless if you are sure that no other dialogs will be shown.

It's not that I have a dependency on that class, it's just that when I have a single dialog that I hide and the hide is resolved I expect it to clean up any changes done globally. 

Since I'm changing routes in the hide callback the multiple view will never be run and the body class will never be removed. I adapted my example to show this in action: https://jsfiddle.net/mu6ww6r3/
If you press "Show dialog", then "Go to page 2" and then open your inspector you'll see that the body class never gets removed.

Maybe the `toShowItems.length` check could also be done in the transition resolve? What do you think?

**Comment by ArthurClemens** [comment]
You could solve that by having the dialog component in the root view instead of in one page. But I think you have a valid use case. Will look into it.

**Comment by rzetterberg** [comment]
@ArthurClemens good idea, will try that! Thanks for hearing me out

**Comment by ArthurClemens** [comment]
This has been fixed. See working example: https://jsfiddle.net/ArthurClemens/z9w63gyf/
