### ISSUE TITLE
Textfield: floating label or placeholder not triggered with integer content

### ISSUE THREAD

**Issue by ArchOrn** [ArthurClemens/Polythene#23]
Hi,

I have a view used for editing a business object and sending it back to my API. In this view, I use some textfields (with or without the floating label option enabled) and populate them using _value_ like so:

```
m.component(textfield, {
  label: 'Start date',
  floatingLabel: true,
  help: 'My object start date',
  value: object.startDate(),
  events: {
     onchange: m.withAttr('value', object.startDate())
  }
})
```

My object is a simple ES6 class instance with some m.prop(...) attributes.

The problem is, if the field is populated with an integer, the placeholder does not disappear and overlap the content.

Moreover, and I think it is a different problem, on routing to that page, the first field is completly out of the screen because of an applied style:

```
left: 1200.25px;
```

And when leaving the field, I got this error:

> Uncaught TypeError: Cannot read property 'classList' of undefined
> onBlur @ textfield.js:115

I did not succeed in finding why these problems are happening. I hope I gave you enough information.

Thanks,

Raphaël

# Environment

## Browser

- Chrome 51 (Windows, Mac)

## Library

- v0.2.30 (via jspm => npm)

**Comment by ArthurClemens** [comment]
Can you reproduce the error in a jsfiddle? See https://jsfiddle.net/ArthurClemens/1wmhfwbs/ for an example setup.

**Comment by ArthurClemens** [comment]
I can confirm it happens in the fiddle. Will look into it.

**Comment by ArthurClemens** [comment]
The first bug was easy to find and fix. For the second one I have no clue. Any way to reproduce that?

**Comment by ArchOrn** [comment]
Hi Arthur,

Thank you for your quick answer and fix, that is awesome. I will try to reproduce the second issue in a jsfiddle.

**Comment by ArchOrn** [comment]
I was not able to reproduce the second problem. I assume it is my implementation somehow which is failing. I close this issue for now and will reopen a new one if I succeed in reproducing it.

Anyway, thanks for the first fix.

Raphaël
