### ISSUE TITLE
Please add all version tags

### ISSUE THREAD

**Issue by nolsherry** [ArthurClemens/Polythene#24]
Hello @ArthurClemens ,
I am the member of [cdnjs](https://github.com/cdnjs) project.
We want to host this library.
Please add all version tags into your project, thank you very much!
![image](https://cloud.githubusercontent.com/assets/8747900/16709240/6b71b2d2-463d-11e6-9d16-16892467b30c.png)

cdnjs/cdnjs#8437

**Comment by ArthurClemens** [comment]
Done.
