### ISSUE TITLE
Add `data-` attributes to elements

### ISSUE THREAD

**Issue by JohnPaulHarold** [ArthurClemens/polythene#29]
Is it possible to add data-* attributes to material elements via this library? If not, would it be worthwhile to do so?

**Comment by ArthurClemens** [comment]
Why would you need that? I can imagine its use in server rendered templates where you need to access elements on the page, but with Mithril you are in control yourself.

**Comment by JohnPaulHarold** [comment]
previous uses of mithril I've had need to do something like this

````
m(
  '.some-el', 
  {
    'data-someattrnotsuitedtoclassorid': someattr,
    onclick: m.withAttr('data-someattrnotsuitedtoclassorid', ctrl.someMethod),
  }
  'Click me!'
);
````

If this isn't something you'd be willing to support, I'll close the ticket. 
Thanks for the reply anyway.

**Comment by ArthurClemens** [comment]
If the only use for the data attribute is to pass around some data, you can write it directly:

```
m(
  '.some-el', 
  {
    onclick: function() {
        ctrl.someMethod(someattr);
    )
  }
  'Click me!'
);
```

If you have other use cases where you cannot use this, you can always write the attribute on the tag:

```
m('.some-el[data-someattrnotsuitedtoclassorid=' + someattr + ']',
```

For use in Polythene pass the `tag` option:
```
m(button, {
    tag:'a[data-someattrnotsuitedtoclassorid=' + someattr + ']',
    ...
})
```

**Comment by JohnPaulHarold** [comment]
OK, thanks for the pointers.
