### ISSUE TITLE
Switching to rewrite version of Mithril?

### ISSUE THREAD

**Issue by lugrugzo** [ArthurClemens/polythene#30]
Right now it's based on 0.2.x version. Do you consider switching to rewrite version?

Thanks for great library.

**Comment by ArthurClemens** [comment]
I have started working on the rewrite in the rewrite branch.

**Comment by lugrugzo** [comment]
Ah, I just saw it. Thanks for your information.

**Comment by ArthurClemens** [comment]
An example project setup is available at [polythene-mithril-rewrite-branch-starter](https://github.com/ArthurClemens/polythene-mithril-rewrite-branch-starter)
