### ISSUE TITLE
Excessive rendering

### ISSUE THREAD

**Issue by jsguy** [ArthurClemens/polythene#36]
Hi Arthur,

I was playing around with the textfield and buttons, and I've noticed that the components seem to redraw whenever there is ANY change within the component, for example even a hover over a button will re-render the entire app.

To reproduce:

- Create a textfield and a button component
- Type into the text field
- Hover over the button

Here is an example using Polythene:
http://codepen.io/jsguy/pen/Kaqqmo

If you start typing in the textfield, the render count will quickly go up, and hovering over the button also increases the render count, this is quite in-efficient.

Here is an example using plain elements:
http://codepen.io/jsguy/pen/pRwwpZ

In this example, the render count stays at 1, using the criteria above.

Any ideas on how we can minimise the re-rendering?

**Comment by jsguy** [comment]
By the way I haven't looked at the rewrite branch yet, does it have the same issue? From what I can see, there are a few places where it calls m.redraw manually, we probably just need a way to limit those - in the [bindings library](https://github.com/jsguy/mithril.bindings) I use a basic algorithm to know when to redraw, and when I bind a standard INPUT element, it works as expected.
I've been a little disappointed with m.prop before, (hence the bindings library), because it really needs to be the trigger for a redraw, (in my library it directly handles events and property changes, etc), not the widgets themselves.

**Comment by jsguy** [comment]
Note: Just to be clear, this is a **critical issue** - for example when you change the name field, the name in the model isn't updated, and even if you try to use onchange and m.withAttr, the value still isn't updated, as the redraw wipes the value.

@ArthurClemens

**Comment by ArthurClemens** [comment]
This is expected behaviour from Mithril. A bound event will result in a redraw. 

The mouseover/out events are used to prevent the button from getting stuck with a focus state when the button was clicked.

Your last comment sounds like there is something wrong in the setup. A redraw should never result in lost data. See [this example fiddle](https://jsfiddle.net/ArthurClemens/64y0fte6/).

**Comment by jsguy** [comment]
Oh, I see you've overridden the events system:

https://github.com/ArthurClemens/polythene/blob/master/textfield/textfield.es6#L327

So that's probably why m.withAttr doesn't work...

**Comment by jsguy** [comment]
Ok cool, so if I do this:

```javascript
m.component(textfield, {
	label: 'Username or email',
	value: ctrl.model.username(),
	events: {
		onchange: m.withAttr("value", ctrl.model.username)
	}
})
```

It works. If I were using a standard INPUT, this would work:

```javascript
m('input', {
	placeholder: "Username or email",
	value: ctrl.name(),
	onchange: m.withAttr('value', ctrl.name)
})
```

Is there any documentation about this? Might be good to add it in the introduction or something :)

@ArthurClemens I still think the amount of redrawing seems quite excessive, it might be good to run some performance tests, to see if it is worthwhile to eliminate some of the redrawing, but let's consider this closed for now.

**Comment by ArthurClemens** [comment]
There is no separate documentation about events, but the events object is mentioned with every component, and some components contain examples with events (Notification, Search, Textfield, ...).

**Comment by ArthurClemens** [comment]
If I could prevent the button to get stuck with focus after a click, the onmouseover/out events could be removed. Still I need the focus to work when using the keyboard. So I am not sure that is even possible.

**Comment by jsguy** [comment]
Ok, I see the events in the examples now that you mention it - though I was expecting it to still allow m.withAttr to work. I guess there isn't much we can do about that, other than to make sure people know to use the 'events' instead.
I hear you about the button focus issue - there probably isn't much we can do about that - and we'll just need to rely on mithril's diff algorithm - it's always better to have a working widget, even at the expense of a slight performance hit.

Thanks for looking into it.
