### ISSUE TITLE
Question about use of const

### ISSUE THREAD

**Issue by rcousens** [ArthurClemens/Polythene#4]
Hi,

Sorry this might be a bit naive but I'm wondering about the underlying rationale of using const everywhere.

Is the intention to effectively make these components immutable once created and rendered? Does that result in a performance advantage?

**Comment by ArthurClemens** [comment]
I am a proponent of using immutable variables wherever possible. It reduces the chances of side effects. 
Deciding when to use `const` over `let` forces you to think how you are going to use the variable.

When es6 is implemented natively, `const` should lead to performance improvements. I prefer the code to be ready for that moment.
