### ISSUE TITLE
Dialog resets scroll

### ISSUE THREAD

**Issue by jsguy** [ArthurClemens/polythene#40]
Example:

https://jsfiddle.net/ea2kw3hq/

To reproduce (as per example above):

* Add a button that can open a dialog, down the page a bit
* Click the button to open the dialog

The page scroll is now reset to 0

**Comment by jsguy** [comment]
Note: I've narrowed it down to dialog/theme/layout.es6, line 159:

https://github.com/ArthurClemens/polythene/blob/master/dialog/theme/layout.es6#L159

It's the `"position: 'fixed'"` that causes the issue, ie: if I comment out the position fixed, it works fine:

```javascript
' body.pe-dialog--open': {
    overflow: 'hidden',
    left: 0,
    '-webkit-overflow-scrolling': 'touch',
    //position: 'fixed',
    top: 0,
    width: '100%'
}
```

Do you know what that is needed for, if anything?

**Comment by ArthurClemens** [comment]
I see. Somehow this problem never happened in my apps or on the demo site (http://arthurclemens.github.io/Polythene-examples/index.html#/dialog).

But I also think that `position: fixed` can be omitted.

I have removed that and updated `polythene-standalone`, so the fiddle now works as expected.
