### ISSUE TITLE
Data Table/Date Picker components?

### ISSUE THREAD

**Issue by retorquere** [ArthurClemens/polythene#41]
Are there plans for sortable/pageable data tables and/or date pickers in polythene?

**Comment by ArthurClemens** [comment]
I will look at new components after the rewrite to Mithril 1.0. Not before May.

**Comment by ArthurClemens** [comment]
This is low priority at this time.

**Comment by clochardpagan** [comment]
> This is low priority at this time.

Great job, awesome framework, you've beaten up Google for sure. But... **May**be it's time to deal with table component and dig another grave - for another framework (shh..., it's MaterializeCSS)?

I'd like to help, but my skills are not sufficient to create something better than a botch - not production ready at all. Hope on you.
