### ISSUE TITLE
Extending Polythene

### ISSUE THREAD

**Issue by kokujin** [ArthurClemens/polythene#45]
First off, hats off to you and the contributors, a lot of work has gone into this project.

- Does this project track the [Material Components](https://github.com/material-components/material-components-web) project?

- If I have a custom material design component, are there guidelines somewhere that explains how to implement it in Polythene?

Thanks

**Comment by ArthurClemens** [comment]
Thanks. And more work is underway for the Mithril 1.x version.

Polythene doesn't follow material-components-web, as it originated before that project (and I dislike what I am seeing over there).

My focus is now to first get the rewrite out and update the documentation of the components. 

If you are working on an app, you can just use your own components next to Polythene components. If you want to contribute, yes you will need some guidelines.

**Comment by kokujin** [comment]
So that means  I would have to load the Material Drawer component and it's dependencies separately if I want to use it?

**Comment by ArthurClemens** [comment]
Yes. You would also need to wrap the necessary html as Mithril code (hyperscript or JSX).

**Comment by ArthurClemens** [comment]
Described in 07177be1b02ea1f4e271db7395f44c561f340bb8

I've added example code on https://github.com/ArthurClemens/polythene-mithril-material-components-web
