### ISSUE TITLE
Problems mounting/ Rendering Toolbar

### ISSUE THREAD

**Issue by kokujin** [ArthurClemens/polythene#46]
Testing Polythene, using code from the examples and building for ES5

````
var btn = function(group, name) {
    return m(IconButton, {
        icon: {
            svg: {
                group: group,
                name: name
            }
        }
    });
};

var toolbarRow = [
    btn('navigation', 'menu'),
    m('span.flex', 'Toolbar'),
    btn('navigation', 'refresh'),
    btn('content', 'add')
];

var toolbar = m(Toolbar, {
    content: toolbarRow
});

var newDiv = document.createElement('div');
newDiv.id = 'app';
document.body.appendChild(newDiv);

var appDiv = document.getElementById('app');
m.mount(appDiv, toolbar);
`````

The above code throws an error

`````
app.js:formatted:4970 Uncaught ReferenceError: System is not defined
`````

further debugging shows that the problem occurs when loading SVGs

`````
, loadSvg = function(e, t, r) {
            var o = 3 < arguments.length && void 0 !== arguments[3] && arguments[3];
            if (System && System.import) { <-------- ERROR
`````

Any idea what I am doing wrong? Thanks

**Comment by kokujin** [comment]
My imports....

``````
var m = require('mithril');
var button = require('polythene/button/button');
var dialog = require('polythene/dialog/dialog');
var List = require('polythene/list/list');
var ListTile = require('polythene/list-tile/list-tile');
var Toolbar = require('polythene/toolbar/toolbar');
var IconButton = require('polythene/icon-button/icon-button');

require('polythene/theme/theme'); // optional
``````

**Comment by ArthurClemens** [comment]
It looks like you are using Polythene 0.2.0? Version 0.3.0 no longer has this dependency.

This fiddle shows your example (a little modified): https://jsfiddle.net/ArthurClemens/srbruqb5/

**Comment by kokujin** [comment]
I'll check that up, I just clone your setup repository and used it as it is

https://github.com/ArthurClemens/Polythene-setup

**Comment by ArthurClemens** [comment]
Thanks for reminding me to update that one.

**Comment by kokujin** [comment]
hmm, no luck. I updated  the package.json file and executed another npm install

``````
 "dependencies": {
        "mithril": "^0.2.5",
        "polythene": "*"
    },
````````
Same problem

**Comment by ArthurClemens** [comment]
I've updated Polythene-setup, version 0.3.0.

**Comment by kokujin** [comment]
Ok, things are working better now. One last problem though. I am getting this error in the console:

``````
A bad HTTP response code (404) was received when fetching the script.
:3000/service-worker.js Failed to load resource: net::ERR_INVALID_RESPONSE
``````
Would I need a polyfill? I am testing in Chrome, the latest

**Comment by ArthurClemens** [comment]
* Did you first run `yarn`?
* Which command did you use to build?
* Did you view the page using the dev server on port 3000?

**Comment by kokujin** [comment]
Did you first run yarn? -- > I did the equivalent, "npm install"
Which command did you use to build? I did a "yarn run build"
Did you view the page using the dev server on port 3000? Yes, "npm run dev"

I just tried it out with Firefox, all OK

**Comment by ArthurClemens** [comment]
Strange, I don't see that on Chrome (Mac).

**Comment by kokujin** [comment]
Tried again using only Yarn commands, same result, using Chrome Version 59.0.3071.86 (Official Build) (64-bit) on Linux.

I will try using serviceworker polyfills

**Comment by ArthurClemens** [comment]
Does it also happen when you do a `yarn run build`, then start a local webserver?

**Comment by kokujin** [comment]
I have the developer tools in a tab open, then I point the URL to localhost:3000.

**Comment by ArthurClemens** [comment]
I was trying to get webpack dev server out of the equation.

**Comment by kokujin** [comment]
I tried a trick I learned in the Polymer forum, deleting the service worker and restarting. That helped. No errors now.

Thanks for your help :)

**Comment by ArthurClemens** [comment]
Good it works now. Can I close this issue?

**Comment by kokujin** [comment]
One last thing, toolbar shows, but not all of it. I dont see the butons

``````
var toolbarRow = [
    btn('navigation', 'menu'),
    m('span.flex', 'Toolbar'),
    btn('navigation', 'refresh'),
    btn('content', 'add')
];

var toolbar = m(Toolbar, {
    content: toolbarRow
});


``````

**Comment by ArthurClemens** [comment]
Check the fiddle for a working example: https://jsfiddle.net/ArthurClemens/srbruqb5/
