### ISSUE TITLE
Source code of the examples?

### ISSUE THREAD

**Issue by kokujin** [ArthurClemens/polythene#48]
Is the source code of the examples on the site available somewhere for studying? Thanks

**Comment by ArthurClemens** [comment]
The examples are in the github repo.

* `git clone https://github.com/ArthurClemens/polythene.git`
* `cd polythene`
* `yarn`
* `lerna bootstrap`
* `cd packages/examples`
* `yarn run dev`

**Comment by kokujin** [comment]
Great, thanks!
