### ISSUE TITLE
Not taking roboto font from google

### ISSUE THREAD

**Issue by vokimon** [ArthurClemens/polythene#49]
The way polythene transparently downloads webfonts api is a clever hack but i am currently working on an application that should work offline and the unsuccessful loading of the font is slowing down the whole display. so is there any way to disable it? Or even prepacking it using tools like webpack?

**Comment by ArthurClemens** [comment]
The webfont download is optional. You can implement your own method.

What I've done for a Cordova based app:


1. Get the web font as otf
2. Git clone [woff2 converter](https://github.com/google/woff2) then `make clean all`
2. Run `woff2_compress myfont-regular.otf`
3. Convert to base64: `openssl base64 -in myfont-regular.woff2 > myfont-regular.woff2.base64`
4. Rename to `myfont-regular.woff2.base64.js`
5. Remove newlines
6. Put string inside module.exports = 'xxx';
7. Import this file where you need the font. I've use j2c to create a stylesheet.

```javascript
import myFontRegular from "./myfont-regular.woff2.base64.js";

const fontRules = [
  "@font-face": {
    fontFamily: "myfont",
    fontStyle: "normal",
    fontWeight: 400,
    src: `url(data:application/font-woff;charset=utf-8;base64,${myFontRegular}) format('woff')`
];

// let j2c handle fontRules
```
