### ISSUE TITLE
Very slow scrolling on mobile Firefox

### ISSUE THREAD

**Issue by mneumann** [ArthurClemens/Polythene#5]
When viewing the demos on mobile Firefox on Android (39.0), scrolling down the page via tapping feels very sluggish, so it becomes almost unusable. Chrome doesn't have this problem.

**Comment by ArthurClemens** [comment]
I don't own an Android device, so I need to defer this at the moment.

**Comment by ArthurClemens** [comment]
I agree that Firefox does feel a bit sluggish, scrolling is unnatural. It would not be my favourite browser.
