### ISSUE TITLE
Ist textfield already in polythene-mithril for mithril 1.0?

### ISSUE THREAD

**Issue by monsterag** [ArthurClemens/polythene#50]
Hello i am trying your polythene-mithrill.js from the "tests-render-html" folder, from the rewrite-universal branch . 
Buttons work fine, but are inputs already included?

            m(".row", 
              m(polythene.RaisedButton, {
                label: "Suchen"
            }),
            m(polythene.textfield,{
              label: "Textinput"
            })),

Also polythene.Textfield works not or TextField.

Without textfield it works, but with textfield i get

mithril.min.js:1 Uncaught Error: The selector must be either a string or a component.
    at B (mithril.min.js:1)
    at Object.view (app.js:27)
    at h (mithril.min.js:19)

**Comment by ArthurClemens** [comment]
Sorry, that test folder has not been updated for a while. With the latest commit, the new build script includes all components that are finished so far.

**Comment by monsterag** [comment]
thanks a lot
