### ISSUE TITLE
TextField ignoreEvents check never passes

### ISSUE THREAD

**Issue by sjungwirth** [ArthurClemens/polythene#54]
ignoreEvent expects a string name
```
const ignoreEvent = (attrs, name) =>
  attrs.ignoreEvents && attrs.ignoreEvents.indexOf(name) !== -1;
```

but is always passed a string wrapped in an array, so the `indexOf` check always fails.
```
!ignoreEvent(attrs, [k.onclick])
...
```

**Comment by ArthurClemens** [comment]
Fixed with 90fd006e5b266e503565557f4cbbf9692a2b2cc2
Thanks.
