### ISSUE TITLE
[question] Is it possible to remove dependence font.js ?

### ISSUE THREAD

**Issue by shaoahs** [ArthurClemens/polythene#57]
Is it possible to remove dependence font.js ?
polythene-utilities.mjs
`ajax.googleapis.com/ajax/libs/webfont/1/webfont.js`

**Comment by ArthurClemens** [comment]
Why do you want to remove it?

**Comment by shaoahs** [comment]
in China  `ajax.googleapis.com` has problem. domain name is  blocked.

**Comment by ArthurClemens** [comment]
What do you propose?

**Comment by shaoahs** [comment]
how to use config to skip `addWebFont` ?

**Comment by ArthurClemens** [comment]
By not using `addTypography` and `addRoboto`, `addWebFont` is not called.
