### ISSUE TITLE
ESC key closes all dialogs instead of the last one

### ISSUE THREAD

**Issue by vokimon** [ArthurClemens/polythene#63]
If several cascaded dialogs are open, clicking outside the dialog properly closes the last dialog of the cascade. But pressing ESC close them all. I don't know if this is intended but i think it should close just the last one as most android apps do.

**Comment by ArthurClemens** [comment]
I will look into it.

**Comment by ArthurClemens** [comment]
89823c8
Solved in the next release.

**Comment by ArthurClemens** [comment]
Fixed in v.1.1.0
