### ISSUE TITLE
Search Field Styling

### ISSUE THREAD

**Issue by hermannsblum** [ArthurClemens/polythene#66]
When using the Search Component in mithril, the input get's assigned a wrong height.

In particular, the property `height: 56px` is assigned to the classes: `.pe-search.pe-search--full-width, .pe-search.pe-search--full-width .pe-textfield__input-area, .pe-search.pe-search--full-width .pe-textfield__input, .pe-search.pe-search--full-width .pe-textfield__label`, where `pe-textfield__input` and `pe-textfield__label` should not be in this list.
Disabeling the property actually solves the display issue. 

<img width="669" alt="grafik" src="https://user-images.githubusercontent.com/5478501/37247274-139fb354-24b9-11e8-837a-a1ee31f2da9a.png">

The screenshot shows how the height of the input field, together with the margin, is making the field too big, displacing the input text.

**Comment by ArthurClemens** [comment]
I cannot reproduce this visual bug. What browser are you using? A jsfiddle or flems could help identify where the problem occurs.

**Comment by ArthurClemens** [comment]
Are you by any chance using a floating label?

**Comment by hermannsblum** [comment]
I get this consistently with the version installed from npm in firefox. The corresponding JSFiddle of the Search Field actually is styled correctly, I can also not reproduce it there.

**Comment by hermannsblum** [comment]
Found the problem: Your current setting are only working with the Roboto font. Standard fonts result in weird text offsets, even tough I cannot really explain how this comes.

**Comment by ArthurClemens** [comment]
Which font is giving you problems?

**Comment by hermannsblum** [comment]
I first had the problem with Din Pro, but when I removed the font-styling I had the same problem with firefox and chrome default fonts, which I think in both browsers is Arial and Times New Roman, 16 pt

**Comment by ArthurClemens** [comment]
What options do you pass to the component?

**Comment by ArthurClemens** [comment]
I don't know how to reproduce this issue. Provide more info here or create a new issue when you have more information.
