### ISSUE TITLE
formOptions for Dialog's do not work in Mithril

### ISSUE THREAD

**Issue by andershol** [ArthurClemens/polythene#67]
It seems that formOptions is ignored by Dialog's when used with Mithril.
When comparing the "form" element created in the React and Mithril examples it seems that the form options, i.e. "name"/"type" (should be "method")/"enctype", are only present in the React example:
https://jsfiddle.net/ArthurClemens/1fgh0bgt/
https://jsfiddle.net/ArthurClemens/0g6010eu/

**Comment by andershol** [comment]
Thank you for fixing this and for the quick response 😃

**Comment by ArthurClemens** [comment]
Fixed in release 1.2.0.
