### ISSUE TITLE
Sliders do not work in Firefox

### ISSUE THREAD

**Issue by andershol** [ArthurClemens/polythene#68]
It seems that the sliders examples for both React and Mithril do not work in Firefox (verison 60) while it works in Chrome. The sliders are drawn correctly and the thumb changes to an active state when clicked, but it can not be dragged to a new value. No error is shown in the console.
https://jsfiddle.net/ArthurClemens/ekht8sef/
https://jsfiddle.net/ArthurClemens/nL12sq4x/

**Comment by ArthurClemens** [comment]
I've downloaded the Firefox 60 beta for Mac. I can't reproduce the issue, sliders are working in this browser. Which platform are you on?

**Comment by andershol** [comment]
I'm on windows. I tested with addons disabled and that do not work either. But I also tested on a clean profile and that works. I can't see what is special in my profile, apart from addons, though.

**Comment by ArthurClemens** [comment]
What's your proposed course of action?

**Comment by andershol** [comment]
When you want to listen to e.g. "touchstart" (which I believe to be the problem in this case), you instead/also set up a listener for click or mousedown (depending on what you are trying to do). It is kind of a touch polyfill but much less general as you only need to handle the features and behavior of the event that you actually use.
This issue also seems to affect the Menu examples, where it is not possible to close the open menu.

**Comment by ArthurClemens** [comment]
Fixed in release 1.2.0.
