### ISSUE TITLE
Can't import the named export 'Ripple' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by jdemilledt** [ArthurClemens/polythene#73]
Webpack is giving me the error described in the title. Based on my reading, it seems possible that this is due to some files being named `.mjs`. Not sure, though.

**Comment by ArthurClemens** [comment]
Which Webpack?

**Comment by jdemilledt** [comment]
```yarn run v1.6.0
$ /home/julian/[redacted]/node_modules/.bin/webpack --version
4.10.2
Done in 0.28s.
```

**Comment by jdemilledt** [comment]
The log is here: https://gist.github.com/jdemilledt/8f436ab3eb8958eb318bf02b90f989fe

**Comment by ArthurClemens** [comment]
Could you check out https://github.com/ArthurClemens/polythene-mithril-setup ? I don't see any problems with the setup there.

**Comment by jdemilledt** [comment]
I'll try and clone that setup and add the Webpack CoffeeScript loader

**Comment by jdemilledt** [comment]
That works. Now, in the browser I'm getting an error when I click the "Show Dialog" button, along with no CSS seeming to have loaded.
![image](https://user-images.githubusercontent.com/29146969/40934364-92a25b20-6802-11e8-9148-aa4b4c497d06.png)
```coffeescript
import m from "mithril"
import { RaisedButton, Dialog } from "polythene-mithril"
import "polythene-css/dist/polythene.css" # Component CSS
import "polythene-css/dist/polythene-typography.css" # Polythene typography stuff

Root = {
    view: -> m "div", [
        m RaisedButton, {
            label: "Show dialog",
            events: {
                onclick: () -> Dialog.show {
                    title: "Hello",
                    body: "Click outside to close, or press ESCAPE",
                    backdrop: true
                }
            }
        },
        m Dialog
    ]
}

m.route document.body, "/", {
    "/": Root
}
```

**Comment by ArthurClemens** [comment]
You still need to load the imported CSS. In the "setup" repo this is done with ExtractTextPlugin.

**Comment by jdemilledt** [comment]
I seem to have forgotten to link to the extracted stylesheet in the HTML file. I'll report back to you when I get a chance to do that.

**Comment by jdemilledt** [comment]
Styles work now, but I still get this error:
![image](https://user-images.githubusercontent.com/29146969/40977365-c045bfbc-689e-11e8-86b9-58bc85177c15.png)

**Comment by ArthurClemens** [comment]
This type of problem is easier to solve on the Gitter channel

**Comment by jdemilledt** [comment]
Ok. I'll join it.
