### ISSUE TITLE
Drawer's dialog-pane max-height is being set incorrectly and causing content to not fill

### ISSUE THREAD

**Issue by cmawhorter** [ArthurClemens/polythene#74]
Image is from a slightly modified [responsive drawer demo](https://flems.io/#0=N4IgtglgJlA2CmIBcAWAnAOgIwHYA0IAzvAgMYAu8UyIAdgIYBuEA5veRAPa0C0sEhchgBWhEAQBmEBGKQBtUAzCIkIDAAtyYWOJClulWuRoAeQqQBOEAA7kABIQukAvAB0Qm8tcJIA9L4t6AHcWCCF9MF8AQQtydQBXCwBhBGVaQl9rTlgATzj4WnhfQoAPckz6UgBrehZ4DKzc-MKeSDirWF8oAXLGvPUC+Faw9Q6eQXpaKHpYbngRQncAPhNfcytbJddaM0sbe0cXd09vPwDg0PDOSJi4xJT4NIbs-sHi+DKK6tr6zJfmoakQgZbqCP5NAYtIGEcbkSbTWaFBbLVbrfZbWjbXTEMgcbiyEBYJAANgADCAAL54RT0ZQ0Ba6fRGArGVT+CBgLKxOzAOwAEUCQXgFjwdgAQvFyORuKKAJJM0UAGR6Sp6ABVpPA7BS7BILNc7O4+gDhu1pO5tkzBDz+YLhaKJVKZXZ5c7lYJVYINQhtXZnHZjZD4ABubYcrn2BjMNh42ju+x6g3uDDFJisdhcXj8QTuUOY2hWg7kCzwWl+uxgDCCEu0vOFuw2QjxMDl9wmaxLRWcEstxvNuxQbLdhxhOy0+DkUVW+AUCeJMfdawCCCkCC0Fh2EhhUXEKADzibiDxQhgTh7yic4dr1fdKDxIx2SV2WD0ABG3a1E-3sxLFdqDDHfgAEd4noDA7AAVXsAoOQXCs11gxgYNpUUQIEOxaE4at4j3D5hVXOFY0fWAXzAfRnzfbt0NoZdH3sGYIDQ6xNxKTd6DsCJT0HDj8XgED2HAvl4nQ+hJS1CALESLVBx-BtaDsEtrBLSEoGFUc1zsRhsniWx2C1JD+Gg4EtVXEj+xkj9N3iXV4lCdgMPiEj2OsegrHYRJwIAURKUh4FseB50INd7E4UhSHoGcBNWDtc0tfF7ERFg1Q+ex-UrYtj3IAAKPsWwAagbbx+wK3KAEo8zi9J7CiaxmP9YBtjsOxuAQ8gkE0zDVL9JYeUapqeKqhx1E4IIBWCYVy2rUswCyiQZmIcq+qagB5V9hBnIR6GBVhaCyxhOvmCZKFFBr5P6prCGG0a7RFJbtUWs6qT65h4CCdqst5I6tQpUrut6s6mvrS6RrGoULEmwjDqu0HhSyh7zpLchEnkmbkxcup3FFO6mtRtQoBungmUMcgeCCQJauFTG7DkbH+pmmGRX+87mY4l9gQAOXHdr3BPGZYHGSx4AKQnOCQiweHx8bweUbpmwFkthcgGiJZuiiLDqeWhd4CRZgzdcValzHafO6xhTASYWXajL4DwY3+uBt6hpBm7bYBlmBuJ9qo3TWN4w+u3zvUeEEBSFcqne37nB6r6q2hm7Zvm+BSoD+7Xfd-rbwACWgeAI7+mOHYZhPYAWux-AcHICwcSG7CCEYeMvQojDtn60-d3GMCJlkqZpt2WZmx1pVoE6U6awIBCoK3JJt0eGygbmiCug2wZ4V9JSHo2+-dl9XxIBeAGUrs39PzvgJCjB8JmT-O7hSH4ao86j6u9Nj52pay63k63lmnu-5nQTfAgeeTtrqGz-k1VuKdcbqCwFTdwGpyAIHcKVNu6dcbdEYFTRKyUyhf3TgAXTwczQhd14bam2BSCqtBKynnvNlQcpBmwsgwO+KAORRQ1WsA9LEBAIhLgQBYGgr43wkGxCQDamYCSkiQAAJgAKyUmpHQccNB8jKAZLwgwLIaDl3DN2ewvIGZJH3vvX0iYWxGn+EGQmwILQFnijaIxJjfT+kDIMYx+8qH1lfDWKoAAFTgwV97mxIuWFAAAOUkdYHE+NLP4wJRgGbBL5uWYkciomVWtLE+g8TgoMwALJUCPC2f0aBSQZPzE4-eGB6AwH3uQHICAsp9WTLzEimthb6DFsvSm4g+qnXOl04UU94gzzdsI6o+NODWBGWM8674LCqQsO1OaJc5najbgMumRT6AAEVRkWByO1AABgAARlhAdiKT4R2CyubEopNoBxHagAEmANk3JiSbrJJIhSawJRSrHL6hSbYD0qk1LqQ0ppLS1AXLlusLWwxlaSzBsfK+OMEKzNQXYBZSysXAs2XdC5eyDlHLsGc4lgFYBjimLcpWjyoDPLsG8j5AS8nfJCdSgqWA-kAppXuO59AHl10ZeoV57zfFsq+VLQpsswC8sBcC0FeZwW1KgPUxp8BmlnWTC+dWQwEXCx1pwPWLAekWDRVspqpsLDmybm1Ow1tsXGtNfit2AAvdqWBsW4uFAAfUCLLS+KACX9KJTs-ZwoyUUp2VS-ldK1wMqZSyyVCTyAFKKcVOwPL-mKsesqnhRBxEUEkTQaRpIeAoHLYomkdJVDexjJmPgPQNF6C0UYHRvgGyXm5C2cxhpwAjA6LFexg1eSumHnYeMnpyDem+uWNxhQvEOJXPicsWzJYSHIJfNshBGAbhKNodIbhXDHClDM-wQQr0YCCAAZgwN2FgvgZHlNJGsfdp73C1yeeoE97gZEhtPSAOwAxWCaD-SAADn7gMvSCGKTgJQIOkjsMhgDdgoNAZWC5OIA4IP5JkVgDAaA0B2HCaQCtGAcAyJ4BgW9OAeCEdvXImjaAUAMco4qLAMjs3oaI3IuwxJaNJBkbR8JAmMBpPQ3YHAGAZFie4+ExgWBSTkezdgIjUnuMyJgcSUghGsAofQyxozMj+YYFJFgBjpJ3X5K49m29ip704BQNJjA4SXN2dvbAcJsniR2BQG5lAnHuNYFve66DvgVjvpYFsPpZ01zvhKAvMw+67CHtgMe6DJwzhXqCDe+9j7n2vui9B79oqIMYa-aBlg4HoOVZgxAV68HEPQeQ6hlz9WsPsHULh6DtmSO3szgF4jpB2NYAMxWwjaAfPhLQOx6b6HHPZrQKp-Tbn5NqeI+hzOWAVv6cM9RjT1GZEADU5HkbG5ZojPBjs3fdWAZDXH1CVtWxJ4k7GmN2FvTwW9X2YTfcY2x77g3htoDOzttASnrMRai3umLaKJjLIHSlg9R7CAQey5e69d6H3qyK+UkrQGytxAq4Bqr8AwPkFJ6V2DzWkMHY62TkAXWcNQDw3Z3AsmcCcZ81geTWB+aEeJGxmTpIHMyO45gAD-MZO7Zo8SLAwWpOYF26RiTv3JeyZQLAORGAUB+YCzgBzuvwlaawOFoDkXUT7ti23YgUxktw7S2jjH56cvY4K3jl9BO4elZFSTurTOQMU5q1TwPNPGtwYQ-T9r6Gmcs562zvrImLPocVzI37dmU8GY19m0ksAsD8eo4X9DFv3BW+i7FihVCPgRgHPAOajl7AfRA8HeAodqj3T+qdPq9YOA+n9C3jgiCbYNgVHJVSrEfrdSJVleMc6R5b2HwgbFTVExGHajNCdi-05w-aryLuG+KwYAyoIHKTJfogq3pArew0xaANzo66eq+MJpkbdwN1LMz4skvla5mt975w5W8pgQ5ADaYr9zofoqFAYHFaBmxCByw5AsB8FoCFI5wLAUY58VR0UQNRZhQH9P9+p+96h2o5B8FO5b4BJ6BapcgsoyDRQ4CwBCAMBzZrAsospGDRQ1xJ9I4eo6DaY-9zpuCPgX8mpl9H93BZRaBEs0UWZV1aB2p5DmCEsEMX9f4WZBD+phCShRDHUwgEAD44QLASwoBZDmZ5DFCrQqwjC1CX9NCmptDdDxCD4WQ-xzQ4t04LCx98QqwCgoBbCBC7ZHC7ZnCB0xot1FgPD3YvClCMBN1t0Ait57CJ8RCQj9CJCQApCZCoi5CmRLCfCVCdDwC7CgiphUi-5Qj3B6lXITCzChC8jvD0hrDXJEiNDSjJ8nD0iXCHxzZ3DdCYirD7d-DijAi-5giKiuiwjAgIi6itCGjYj4jCBWjmZkjxj05KjMjpCENZiHD5irDCjljzpViyiiiJiR9DCaiqAdjGj8imjEdDj+pjiOi0jziB195XDejYBriBifChiHimonjyj1jJj3Bwjt1vi9ifDFj-icChCTjOjXjJCtiSgISP9GjlDkSYTATTjgTESQBqjjCricjzDIS7ibCRikj2igT3YNj3iej6A+igjSTmC-iKS2ixj4SXiDCpj6AZjiT6i0SFjpiEi2SViqScSaSQTNjsj+jmSMADjRSjjxSETuSqijDaj+S5jBTBjyTr8SiOTnizjVT8SPiGSvjNTdjtTfi-CsTlSuSMiwTIjZSrSmjoTFTHi7SjSMisjtiLSbj0T5TMT3SATPTcTjSCSNTnSFCAz7jgzYStDOSvTuj7BPjUTozYjWS9TRjPDEywyHThSnSmSXTmC3Ssy3ZCFSpSoWDqCP5NQiEoDq9C0cQJF8QaAsB0AkBwka1lE601BoRGR21WQ1B0YtQtl6V-cxUvsX1-k8wmo8CLBjVHZ1BoBVJaBZyAwsIwhMx2oSwXwOAkI8wr84iCZD8SYyZqCbUr5QRrAXwyUdYPh1zqtNAvVylGB1B1yJyXzSRGAgh1yJkqgWB9R7xgEABiCQUkcC8Cw87YCg5kB8LZFyGANcFgdqackodc+5JNSciJUkGcihbYc5WNO5RNT8uwMpXCvlLZDAU2c1HA82dWNcVCii9ciAuwECh2c1VedebgHA6828r2OYFi-C2gMRXEUtVQctG7W9JAckCkfBAgfgWgKoWQBQHslQQdM0WAU5Pc+oYwAgRIHQVQE4Hwfwe8awACigyINoUYaQU5NbYkXwayjoVtBpU2GgNEWwbspQdSpy6QWEGsMAbSvSQQXQAymgYys4MyiyiIRyodPyqaWkOy9TN9BKysUQXQVy9Sjy4wOSikIAA) (i just added more list items to overflow)

pe-dialog-pane__body has a height of 0px and pe-dialog-pane is using the max-height value of "calc(100vh - 2 * 64px)" 

![image](https://user-images.githubusercontent.com/142338/50118255-ffb94480-0203-11e9-83fe-e4f2bcb7d99c.png)

**Comment by ArthurClemens** [comment]
Fixed in 1.3.3
