### ISSUE TITLE
Erroneous calls to onChange

### ISSUE THREAD

**Issue by andershol** [ArthurClemens/polythene#80]
In some cases the onChange event handler for a TextField is called even if no change have occurred. For example loading [this test case using the current "master" branch](https://flems.io/#0=N4Igxg9gdgzhA2BTEAucD4EMAONEBMQAaEGMAJw1QG0AGI2gXRIDMBLJGG0KTAW2RoAdAAsALn3jF0UMYlmoQAHjLk22MQAIY5MAF4AOiHFjcKAPTnymAO5CA5mzEjMYANZDIfcwEFyzgFdyAGEkAVhzbAQAT2d5RHM+TBg5ckjXN0x7RBhImLioRABaPicRNXhzfDYUvPhYkXiSsoqilMwofEx4aEQhACsYIwA+JXNVdTFhgyglaoA3TTZ8QxBKCDERsYXh6TwkMDE2aC40WhQANgB2EABfIh5+QRABrhJIWXkxRQ+UzWBNAAVRAADzEADE2Ih4PhNLdNHpNFF6gVEABuGbzTDkTTzKE2YIQAKyBGaeiaMAuKDZQnErSI2gYqBYnFY+ABHKk6gAcnBEAg3KImm5ACFsYLhWKAF7cxhM34IPo9ewACm5PUwsKK2p1uu5AEomTNflofNhsKTgDNNLj8ShNCxiYdjlAVfr-tabbbEASibIANT+tGaT028iIMRBKCaPhqwWhr2x7nYCXcox4n1GCndJD4e0SjO+ulC7maI4CGAGogJm1JlMlozQYJU7JZsA5gj5oWUjo0v1iEtltgVqs13HdDkwIRJbAqlUAfSFbHdemGMZVwLBkOh+CFVujXsPWAARtD85utOwd8LNP6ltWD4ebWyOfaXzlqGxmGObU2W4h7UQRZVw9R8nxtBUkCEZU1R7alEBvO82FvYV8xQoChHfQ0fy9OC+zpQMmXAw93xgT9GFJDD3yI4jbjHW59UYmi6KgW4mT4ad+xVfAIDAAJwjEBwIwAUTCL4RWiABJfAVSMdZNhAfUhTNbBsKgGw2E6CA7GgYkNVhRE3QRNdIKVCBVW5PSIE1A1gz2aFEGdE5FAARgADhQABOO5mBAeBNLcU5qEeARFFKZwKmkIIpDQEwzEsYlsDcexPAgbxwvKDgAAEXKEXKLkSFoOFeaQxGibBngmDQfNuIA) shows 6 calls to onChange by just loading the page and after focusing a text field and defocusing it again shows 11 calls, when no calls should occur in either case.
Loading [the same test case using the current "next" branch](https://flems.io/#0=N4IgzgxgTg9gNnEAuA2gBgDRoLoZAMwEs4BTMZFUAOwEMBbE5EAOgAsAXOxPCGK9kvyYAeSFEIAHdgAIwUCAF4AOiA7sJYJAHotUGgHdmAc0LtWNCAGtmvOloCCUMwFcoAYVIMqYLRPgBPM0ESLSoSAA92XwtLGiMyXwCgsIBaOlNWcTgtABNCMCi-OEDWYLSMrJSCmiocmjg+EmYAKzAVAD5hLTFJdnalKmE8gDdpQhzlEFgYdg6ukfaQPDASUgh2Qj5yJBA0JAA2AFYQAF8ManpGHZbyHj4BIR3ebxlgaQAVCPYAMUJVnOkJ2kCmkRRKwQA3ANhjQoNJhn99G4YM5+MDpJhpBBzFR4sjUTIQWgoVQYXCYXBnGR0SgAOTfGAwWkYaS0gBCsOZrI5AC9adgSc8wPAmg0jAAKWkNGgAlJy+UK2kAShJAyFMnsEgk6OAA2k8MRSGk+FR602VHFSukuqo+v1CJISJR-AA1C6IdI9XaoCR2K5bXRJcyvXbpIHaRIubSVA79CosfVSDkjVzY-j+CzadINgwwMqMCG7eHI5mVHw3Dj4vGIImSMnWSzsTU8c72Jns4Rc-nC-b6lSwMw6DQJOLxQB9FmEK0Kdph8WfSK-f4sm2h0NwGgAI1WKYXMiI-1Z0hdYwLtrXvcpJCNFP7KEIuB7dvLlev0hIoxn1qfoaFIuYYqSk2uIkEeJ6EMerIppBH7MLeJAqj+drAS2BJuiSF6hvBYD3tg6KwfBGGYScT4nEq5FESRVAnCSdCDq24o5DAEDOF47DGL6ACiniCOwbL+AAkjk4oqNMswgEqLKahIiFUPohC1DAhh8Ki0oAiClrArOf6kABMASrSqkwDKyoeks4CrCQZpbEwACMAAcSAAJynLgIBwApljbJQIC0AwTDpGYWTma4iA7GoGjaFoqISJYRg2DAdiBZkxAAAK2cwGX7FoyVZDc5nsP4EhXOA0C9K5JxAA) shows 0 calls to onChange after load (which is good), but after focusing a text field and defocusing it again it shows 10 calls, when again 0 was expected.
(tested in Firefox and Chrome)

**Comment by ArthurClemens** [comment]
Note that focus is also passed in onChange, so it makes sense that a focus + a blur results in onChange calls.
I will look into the others.

**Comment by andershol** [comment]
Okay, I had not noticed that. The it might just me my mistake, that I am using "onChanged: ev => ..." instead of "events: { oninput: ev => ... }". It would be nice to avoid the "events: { ... }" though. Thanks for pointing it out.
