### ISSUE TITLE
Minor CSS issues w/ Search

### ISSUE THREAD

**Issue by MynockSpit** [ArthurClemens/polythene#82]
[This example](https://flems.io/#0=N4Igxg9gdgzhA2BTEAucD4EMAONEBMQAaEGMAJw1QG0AGIgdgYA4BdEgMwEskYbQomALbI0AOgAWAFyHxi6KFMSLUIADzwuUANYACCeUQcAvAB0Q0qbhQB6G5nJSJAV3JgkI2GIDmXJ84AjMS4Iexg8KRgbbAQATydlRBtEAA9hbF4bDg8YMTBw811DeDNSKVjeCUREKXMAPlMoRrUyci5sKV0YN1LLazsHfzcPZVzffyCQsIiomPh4qqgkmClMKHxMeGgkuYXEgFohPwMeaLiEpcPjtvh9lbWNraWxACsYerUbVvapBqaoFoUH5dHrmPowWz2RwuYaITxjY6BYKhTDhGqzc6LZardabbZneYXRD7fIYwlYknhO44x7bV7vEB1T7fDp-Zr4LgAN10XHwpUoEFqjM+HM5dXkeCQYCkIVgqgALCgAIxK+UgAC+RAEwlEIHp8kgimUUlUhpWumAugAyogHGAJERdABJQ0AIWcUik0EdVokmHwEAA7rp1bpjLpdkSANyNRpmzpcQ02u0SK0ANQA4mHdOYWpzvLpA7ynGZTOYAEzysuFKpcbzSUsVqtlkC6TlcRCB10QFKNkC0XQDyu6SvV4XYTBOXR8scAWSVAFYxAvdKqJPsxAwAJy3MTl5gb8sMADCi7E8qVq-Ly63q4AbKulWIVffdFvl6+l1vL0qAMxiWhb1-N8P1-K1gK-S9gPfFdINfGD7zAJ870vAd-0AjcF1veU91-fYnwXBh4D3Bg92YTlNx3FccK3LcABly1oc9byVHd9hord9gXAAvIR9gfWhj1I2gf3lXQVxVMRaPEkCFytYTLxXBCJLEhTVzEhDJOk1VZPU7ixxsJkvnzBoQBjKB4x5N1MDAbR0yzcNcxgfNC2LCQ+1HFt9EQOsGzHTzCnbTtu17McByHMSAvHScJGnPtZ0Yx8AAlSOYX94CXLCuJvOilXLXR5VuZhdGK0rV3PJV8IqujUuAv8ksYzl9nLfSW0M5kTPMczLMTaBjyQBx7OzJyXKLfAS385sax8+spA8qbWyCrsez7cKR0ihamQnKcZxbedbzvaqlVIrCZLy1cmNOw6Lxkldrp-S6WPyiSToOirVye1d-xu46bw+-7ftOv93ry1rzHa4zvFM7roHNXqoFnRMhsc9RnILMaJpbKLvN8ubJrHNsO2W0KWzW4coq2mK4rnc7VSQsQ7wEkcpM4p9f0iln9l-XLYLAWgqsZqr2a5kWwKAsR2bfcTOTvPnysZ8rJeA5XeKXPDfzlvDrwXMSl0qtXxOfK1DoYdTdBN5KF0197rwYfLDvLYCHxN8s03LJUJHLJr-33MAfYPc9irvLmJfN-jN3LdcnwYMGQAhtHodjCzYc6ChbSUZM3AkAAxDt4HwbMAAoAEowzqC1Gl0XQeqTW0s+zIQxCkchnBWQv4cz+17OL8yq5r6BXRsvRw0b5vW6kdvrNs7ve+rlOrL6gbyAbpuW7b+H+rrmfK7n2AE0NRGwBXsf14PpHMx7pO+-nwfbPdT1oGzYAd6rpaUF0QvLUnZuYBDUvjD+FXIBughCFxdAPD0XooCOmflAYBwD4bv0tGjd+8Nb56E1C-eBWhtDvw4JsPARAsHAMQJyY0EILS6GgO4RMuDdDf3ILkAaZCQxELgfA9Uxcd7qnMjvSym8HD3ygU-LBb8P5f09Iwv+ZdiEgLAW6SB3oK7sPgQvKASCuj5lQYaARy9MEqOwToPBBDEBsNUVXUh5CNHUM0LZd+DDcjuDrqw2RnDuG8PYZZTuEhwFwPDLA4BYiS5lxzAYquoDfFCKUQE8xiDKEoLUd4lxYSgFaBsjKMh78x6mNcVw9hPCr673NIfXxIiDFBP-uXWRESFEP2gco8xaiNEJPhofZJjS0nSi5IgLJLcckpLcfkjx1895dFWEoMpgTNjOB6TmEA5gzFAIiE6KA2APRWnGbM5w6wjBaAIIsvuS937BIAWMyciAxDLNWeszZn82zTNmeYBZugOAQDAK3XpMy-4HN0Mw2ZJzy73CUGITkDzhrzPmUMneO9DBSFcHAmJr8ibHIkT-aRpzEVAMsqC+AXzwxAouTimZs9gGwvhXI7xjoADyAQXiIGlGIVEMA6xQELrIquwB9GNMxaopQKQpDcEQPnJB7L4FYACEK9+5hvELNFcAvqfooDeH+ZaIlpiug1BWWsqQGzznovLmylJjSCUgrBeGNVPzGlVxNVc7VuqJn4s1dcnVmy5VAOLpa8xFq3VcqtQERRsARVGvgVAbYQarXwIla8ww79QHeN8R6t1wDMAcCUOQWNhcSmGjyRGquvqI2vPeRQnlfqjAQBjXI9BUT6mWj+e-E1fzvlJqASmtNGas3QBzbm-NVrC2twAPockcLEcNuaq5RvLbM0BVaA0wN+baTJZzgWNs4Z6xprbEDprkbo6tc6nEOHrZsvIS8-7Np7Y0od5RR1jonRW6dQ9d2ULrUui5K7E3BtURurdoCd2zsofurdJqAOno-UA9UPq11ANvVOwuvp-RBi7ao89LbJHvBScXS+BjwNQqgAU-4Xi672lzkKgu4Y07nO8cR-OJcPGWQAILYGwJMwmnZjmVN0NQLBoDzBiEoIGMQoalDPM4yk7jIBMDPJLVXAwRgpUWE9P0KEQwnHwh8IiSYoRIwUnwHCCAUQjhOBuDYAAxF8QjEhZXBtWOQZVUg5P9oCFgHQTyBmOmldUeh8A4DvwAAqYkSC88tuhEaGZ4LofY1pzPTl0+YRDuhWDvuAWJ3jQZhPVLZXqGUUgkDPPcymWLnrkuQCEDEJYihLONLjeZqj+A4tVziwlxZrBGh4caI3IQEBtkTwDO8zwUgfA1AAKIjEUK6WITp8AZYFEKD1ugGPYEwxKIV9KZSw1ULQFA-MVSKloBqLUIBBAiFUHkcIBpoBKBUGgDU7AQCaB0HwFA1BtRHbQAZk48AAACSx+XyFcHINA4JITbOwNobweQIBCBsG9m4H3rxMX5m4BmUPrg8DEEcKA+oSDlGwLqFkJp1SsHVEAA) has a [couple bugs](https://codesandbox.io/s/vigorous-bush-0qths) in the latest version (1.6.4)

- Padding causes the input to be off screen
- "Placeholder" text doesn't use the same font

**Comment by ArthurClemens** [comment]
You need to add:
```
import { addTypography } from "polythene-css-typography";
addTypography();
```

**Comment by ArthurClemens** [comment]
With release 1.6.5 this is no longer needed, as the reset CSS is now automatically included.

In your code sandbox you do need to import the local CSS file for it to work. Or check [my updated sandbox](https://codesandbox.io/s/white-water-uhwlk).

**Comment by MynockSpit** [comment]
Great, thanks!
