### ISSUE TITLE
TextField with oninput event in Safari will jump the cursor to the end of the field

### ISSUE THREAD

**Issue by ArthurClemens** [ArthurClemens/polythene#84]
See test case: 
[flems](https://flems.io/#0=N4Igxg9gdgzhA2BTEAucD4EMAONEBMQAaEGMAJw1QG0AGI2gXRIDMBLJGG0KTAW2RoAdAAsALn3jF0UMYlmoQAHnhsoAawAEI8ohYBeADohxY3CgD0FzOTEiAruTBIBsIQHM2d+wCMhbCGsYPDEYC2wEAE87eUQLRAAPfmxOCxYXGCEwYONNXXgjUjFIzhFERDFjAD5DKFqlMnI2bDFNGCdC03MrG28nF3lMz28-AKCQsIj4aLKoOJgxTCh8THhoOKmZ2IBaPi8dDnComLnd-ab4bYWllbW5oQArGGqlC0bmsRq6qAaKD7aOsYujBLNZbA5+ohXEN9r5-IFMMEKpNjrN5otlqt1kdpidENtsijcWiCcErhjbutHs8QFVXu8Wl96vg2AA3TRsfCFSgQSq014s1lVaR4JBgMQBWCKWgoWjbABsKAATABGEAAXyIPH4ghA1OkkFk8jEikNC00wE0ABVEmIAGJsRDwfBETQAJUwbDw+AAQvYxGJoJp1Zp9JpNniANy1Wpm1oAeSgAGEREt3IgbQl7Y7naHNAAKACUoaqFtqmk0cbaizkeeA5YrmlZq3siBQmmMcAEmnwekw9ngrTkWeMRAb6obDd0YkcUDLc8brMdAHd20WS-PG42q834K289c5EJd63owut1WQgBJKDYf0AZRriAPT6E19vD6fZ63Fens80fD5sYgqjpo1ANj+AH5pm2ZOi6m6QY2vYsP2g4AGotm2TaYWO56IYgrLGiCCGIY20BqHeYjts++iloeiDHpheYMYs5DpmIjF7ogEGIZqPGQdAKZplhczLo+mC1rRBb8Yh9GcfuYaieJR4ntxeGQYWuGkRWqlabxmkyRWgHAWyoEAAYYVx7YACTAKp6pmYWMmMIW36NhOC7qmeXkxlAVYAILYNgdYNkuiCrgWxZSeBeGAYmQlQOmMEOnBTkLowtQ+d8fBCHwED2LI+b4BAYD2K4HHsQAogMsg+pEV74EBIA8nymmaIF2CubUIpOog4qSlwaBKkqKAAMwACwalqIC8AIihZMEBrQHIChoD4ED4JECHYJg+Asol7ZKrQ2AJN5PVihK0CDSAKooCq8oaswICqBog3UNqc1oHsdgXAAAnMWbSI4UhoMCoIFdg6juFkEB8BY30HPAv1KkItCo9sThCPK8PnBwuVqPqJDFNguoMia6qMOqQA)

**Comment by ArthurClemens** [comment]
This is an implementation error. The value should not be passed to TextField. Here is an [updated flems](https://flems.io/#0=N4Igxg9gdgzhA2BTEAucD4EMAONEBMQAaEGMAJw1QG0AGI2gXRIDMBLJGG0KTAW2RoAdAAsALn3jF0UMYlmoQAHnhsoAawAEI8ohYBeADohxY3CgD0FzOTEiAruTBIBsIQHM2d+wCMhbCGsYPDEYC2wEAE87eUQLRAAPfmxOCxYXGCEwYONNXXgjUjFIzhFERDFjAD5DKFqlMnI2bDFNGCdC03MrG28nF3lMz28-AKCQsIj4aLKoOJgxTCh8THhoOKmZ2IBaPi8dDnComLnd-ab4bYWllbW5oQArGGqlC0bmsRq6qAaKD7aOsYujBLNZbA5+ohXEN9r5-IFMMEKpNjrN5otlqt1kdpidENtsijcWiCcErhjbutHs8QFVXu8Wl96vg2AA3TRsfCFSgQSq014s1lVaR4JBgMQBWCKWgoWjbABsKAATABGEAAXyIPH4ghA1OkkFk8jEikNC00wE0ABVEmIAGJsRDwfCadWafSaTZ4gDctVqZtaAHkoABhERLdyIG0Je2O53uzQACgAlO6qhbappNAG2os5AngJms5pWat7IgUJpjMYiEX1UWi7oxI4oBnW8XWY6AO6VlNptvF4s50vwcsJ65yIQj8u+9uDpstzR8RPGQU1zTUIuDrPL6Oxp34IgD7eDlKYMCIEQIfCIciV4xWyLYRCaJYzNTuIRfmtbk+aG8sJg9jwGIABqZYViWEG1nOf6IKyxogsef7FtAajYPYYiVi++jphOiBThBCYEYs5CRmIhGjogv4npqNHFuqyYwShy6rmy64AAbgVRlYACTAPhlHluqHHJvRjDJrOg71u26qznJfpQDmACC2DYAWRadogPZJqmuEbr+y7BmGEZRraDoHmJ7aMLUCnfHwQh8BA9iyIm+AQGA9iuBR5EAKIDLIABCkQAJL4CuIA8nyTGaKp2CSbUIpOog4qSlwaAyiqADsGpaiAvACIoWTBAa0ByAoaA+BA+CRMe2CYPgLJQO4lZKrQ2AJPJSVihK0DpSAKooCq8oaswICqBo6XUNqhVoHsdgXAAAnMMbSI4UhoMCoIudg6ifpAfAWPNBzwItSpCLQF3bE4Qjykd5wcI5aj6iQxTPooDImuqjDqkAA) to demonstrate this.

I will update the documentation.

**Comment by ArthurClemens** [comment]
And an [async example](https://flems.io/#0=N4IgzgxgTg9gNnEAuA2gBgDRoLoZAMwEs4BTMZFUAOwEMBbE5EAOgAsAXOxPCGK9kvyYAeOISoBrAASsoJfAF4AOiA7sADmCQB6bTSjtWAVygRSDKmGYBzQoaMAjZoRh6wYEuzDb18AJ6GgiTaJAAe9Oqk3vjmVhDuKlJycMrg7H5RrCSeKgB8SlQFwpBQhOrsUmCmqWqaOnoGxqbmgla29k4ubh5ePv6BVMFg7DRUACY0cHzBvnABWYMAtHR2ssR9cwMky6ulcIvDoxNTg8wAVmB5wtolZez5hVTF0HeV1Sq1Wrr69s0kFm1Vo5nK4aO5PN5ZvMgjcRuNJtMNtClvFIf0FttUQc4cdpudLiBctdbuUHkUxoQAG5SQhjVKwGDsK7aCmU3IgPAeUgQdguSxMNBINCLABsSAATABGEAAXww1HojCQLAuHJAvH4gnYTA1wykwCkABUwuwAGKEEhwMZSGVSBRSKFbADcBQKuoqAHkqABhVijawkY2hM0Wq12qQACgAlHbcvqClIpAmpO7KiMBOHgMnE5TJkYSEgkyAVBgpLopLm4PmaWApEZ1BMBNb8LA6FI+OJ1EYKkdE3wJCQ-GMYAB3KhSXsUsCRGh+EjWmgVQJSByM9gwOjZyqeACSVC77AAyumC3XxvJxPPS+WjB5revtz2K3mSA7YNYoPQ6IvCBBJnMt0IMA9zsedC3wSYPAwZMZWTZM5HYExxyzcdEwrC0R0LCMDUXdgoC0fUpAEYNTVbABBMA-CoCAbRtGMFDjFC0LQwh8EjYizXIyjqKkABCBR7SMc8iEGa0ADIxL4w4BGcYCqFA8TJOkkhmB6PcD2PRcSBjJjmLQ5TVN3fdu00gRsOfKtTw40iNwoqiaJlKMXVQvS0y02SQKbcM8PzZzXNtLdEwQpCpDoCMVFZEspBQQK0LCoMQ0tMZS101zExnCASFYeAxhIKBCxUQ0-HUV9RnmcRrGYKqS1i5isjgdQCpAIqSsqDdXw40sYCgN8yFrZcACUdwAcQACUNKQyIGgaPQAdSkABpABRABNIiYBpSw8qfCA-U-Hk8rfGAPy-H8-wAjlarQvhfX9U9BhHUzXwYyMruYgy1OMo8T3DB6nsM9h1JMk9oJctLEwMytq3tP6T2YKGSDeqQo1B8HExISktQI1K0Y7L7C2euNIZfcMVJGKAA3YeGX1RtG+0kQdhzHAnY3jMG6dYyMVIHPw7QEosyKgWARwGwhrA4RIAB9JakbnBz5+0VFF8WmRAHSkdcj6jI0k9zIRwticsqQAGopGPUoqEqlsN1uqBvRgXKIwATgAdhNqQAFlF1YZgYhgbqIy9wxmE-cYN2jKQACopHFEUoxjRy-LptDYPZtLU7pjP05Rq6woiqkooAAwANRfQsABJgEN-MZULqNYuweuwazmVnNb11qL4PUyPUdRwwjl7dNIHtKIgBKk56Q1CAYGBuwjAe43CsGwT8MeTXDQrWCAmspGttsV+omqwboEP50-Edo2TFGpBFNA0CcuDUOCqBkK3SkMKw+i4zCr1bstwMTTmiSilIigCuL2ULCvNewY6IwQKO3R4J86Cz34BGYcEAjAWCppTJaLR+AACE-A7jGOFEADJVbXx7uoB+VA1S8DoOoYgeUmAOBoA4S0aouQkB5HycgyoAAs-CkAillPKEAtAGBMGYKiOhfABBCGVKuMYvNdLqBoGMCkltCzijQOoUIbdOGWm4byLuTBJRIElCImUuAQBiEkHwyg4jFRMBWIYPYAABQYwY1QmEQMqT49QhLqAkJVeh2hXFrDgO48UzA0CxMWKYZgIpwm7GIMwFYVB8RqnSCVJgJJtTWJlEAA)

**Comment by andershol** [comment]
Couldn't this be changed so it would "just work" with changing value? Having to grab and hold on to a setInputState for each text-field and risking them get out of sync seems quite cumbersome.
It seems to "just work" with plain text[type=text] (even on safari): [flems](https://flems.io/#0=N4IgzgxgTg9gNnEAuA2gBgDRoLoZAMwEs4BTMZFUAOwEMBbE5EAOgAsAXOxPCGK9kvyYAeOISoBrAASsoJfAF4AOiA7sADmCQB6bTSjtWAVygRSDKmGYBzQoaMAjZoRh6wYEuzDb18AJ6GgiTaJAAe9Oqk3vjmVhDuKlJycMrg7H5RrCSeKgB8SlQFwpBQhOrsUmCmqWqaOnoGxqbmgla29k4ubh5ePv6BVMFg7DRUACY0cHzBvnABWYMAtHR2ssR9cwMky6ulcIvDoxNTg8wAVmB5wtolZez5hVTF0HeV1Sq1Wrr69s0kFm1Vo5nK4aO5PN5ZvMgjcRuNJtMNtClvFIf0FttUQc4cdpudLiBctdbuUHkUxoQAG5SQhjVKwGDsK7aCmU3IgPAeUgQdguSxMNBINCLABsSAATABGEAAXww1HojCQLAuHJAvH4gnYTA1wykwCkABUwuwAGKEEhwMZSGVSBRSKFbADcBQKuoqAHkqABhVijawkY2hM0Wq12qQACgAlHbcvqClIpO7KiMBOHgAnE1JKZMjCQkFIVGAYAwpGN5DQjHAKgJgyoMJmZZnM3J2CYqPGO1nKRaAO4FylUGDl2OdrNZ5M5uB58OHATMKd5l1d8et9tSOgRgDkW4bK-HG+3u8PW-E6iM7GPBr4Z4vBZIo7nJAXuYf9ufIygAfYL+nJAw2avjaUZRnuB5ZpuO4AZBt6XgB15ULB96Pqmz6Lm+Ugfvo36-nmAHocBoGZuBm4qKy9ZSAABgAaq+BYACTAOhMqUVGxFZlGy7jk2XYysufGulQyYAILqOo6aZj2JD9pGMYKHGm5er6-qBia5qWmMbFUAJjx0MwdAwEY-ARmMMAQEYFg-t+ACiLT8AAQn4ACSYwRioDJMiAoFSKJ6icQUapciQPJ8uQyqCpKADssryiAtAMEwzComqGoCEIyoOMOfhjg6NBjBSVDWAW4poOooT8YFlrBbyfBhSAkpIJKIqyrgIBiJIYWUHFipMCshh7AAAoMwZqiYiDKp89RGeoEjWElJbaH1axwAN4rMGg62LKYzAiotuzEPp4j4mq6TqEq4AvOULUykAA) and [async flems](https://flems.io/#0=N4IgzgxgTg9gNnEAuA2gBgDRoLoZAMwEs4BTMZFUAOwEMBbE5EAOgAsAXOxPCGK9kvyYAeOISoBrAASsoJfAF4AOiA7sADmCQB6bTSjtWAVygRSDKmGYBzQoaMAjZoRh6wYEuzDb18AJ6GgiTaJAAe9Oqk3vjmVhDuKlJycMrg7H5RrCSeKgB8SlQFwpBQhOrsUmCmqWqaOnoGxqbmgla29k4ubh5ePv6BVMFg7DRUACY0cHzBvnABWYMAtHR2ssR9cwMky6ulcIvDoxNTg8wAVmB5wtolZez5hVTF0HeV1Sq1Wrr69s0kFm1Vo5nK4aO5PN5ZvMgjcRuNJtMNtClvFIf0FttUQc4cdpudLiBctdbuUHkUxoQAG5SQhjVKwGDsK7aCmU3IgPAeUgQdguSxMNBINCLABsSAATABGEAAXww1HojCQLAuHJAvH4gnYTA1wykwCkABUwuwAGKEEhwMZSGVSBRSKFbADcBQKuoqAHkqABhVijawkY2hM0Wq12qQACgAlHbcvqClIpO7KiMBOHgAnE1IaOx2FAAGqTIwkJBSADkZYwmcTlKLJakKjAMAYUjG8hoRjgFQEwZUVaoiZlmczcnYJgHGYHWb40BIOfrlKoMDbsZT8+YObzhbgxfDi+XJA3uagVlrO5I-azUkpFoA7qX9yuFHHJ1fE4R8JHDgIj1u61IAEJ7UfQ9NxPZgz2LGNXzfRNv0PSCSD3Jc21-cDEJdKdYPgtDt13YCUNA49TzrTDYKHLCs2TRDwxwjDqyzUdxykOgIwrS9YJYtjKy4stxHUIx2B4g0+H4wTSyQ581x-Gj7UPEYoADdgILrDBr3-GUoyjDjYNY9jeLEoS1JEqhDIk1c6P-OTmAUpSVPPNSaM07SGKvViVFZPspAAAzw+sABJgEQmVvKjVypCjMiswowdMJlTC3T4PUAEF1HUcNo1XGDSAqME-AgIMKntCsop6Q1CAYGBBIjTKpIjBi8oKk1wxUQ1WEIMAaU6-BYDobMwD8KgID7Bi6GYOQxigGhb2jTNtKkEU0DQSLhynJioAnBibxIe9IxjKTWK9X1-UDE1zUtMZjPU89S0awqbTCqcKPi10qDGugqv4CMxhgCAjAsZSlIAURafgACE-AASTGeqQAZJkQHm1L1BWqg1S5EgeT5chlUFSUAHZZXlEBaAYJhmFRNUNQEIRlQcZc-HjKd1BoMYKSoaxS3FNB1FCOL0ctTHeSSphJSQSURVlXAQDESQccoEnFSYFZDD2AABQZgzVExEGVT56iMKh1AkawKebbQVbWOA1fFZg0DtxZTGYEULd2YhmBWKh8TVdJ1CVcAXnKKWZSAA)
