### ISSUE TITLE
Re: TextField with oninput event in Safari will jump the cursor to the end of the field

### ISSUE THREAD

**Issue by andershol** [ArthurClemens/polythene#85]
(It doesn't seem like I can reopen issue #84, so posting this follow up as a new issue)

Couldn't this be changed so it would "just work" with changing value? Having to grab and hold on to a setInputState for each text-field and risking them get out of sync seems quite cumbersome.
It seems to "just work" with plain text[type=text] (even on safari): [flems](https://flems.io/#0=N4IgzgxgTg9gNnEAuA2gBgDRoLoZAMwEs4BTMZFUAOwEMBbE5EAOgAsAXOxPCGK9kvyYAeOISoBrAASsoJfAF4AOiA7sADmCQB6bTSjtWAVygRSDKmGYBzQoaMAjZoRh6wYEuzDb18AJ6GgiTaJAAe9Oqk3vjmVhDuKlJycMrg7H5RrCSeKgB8SlQFwpBQhOrsUmCmqWqaOnoGxqbmgla29k4ubh5ePv6BVMFg7DRUACY0cHzBvnABWYMAtHR2ssR9cwMky6ulcIvDoxNTg8wAVmB5wtolZez5hVTF0HeV1Sq1Wrr69s0kFm1Vo5nK4aO5PN5ZvMgjcRuNJtMNtClvFIf0FttUQc4cdpudLiBctdbuUHkUxoQAG5SQhjVKwGDsK7aCmU3IgPAeUgQdguSxMNBINCLABsSAATABGEAAXww1HojCQLAuHJAvH4gnYTA1wykwCkABUwuwAGKEEhwMZSGVSBRSKFbADcBQKuoqAHkqABhVijawkY2hM0Wq12qQACgAlHbcvqClIpO7KiMBOHgAnE1JKZMjCQkFIVGAYAwpGN5DQjHAKgJgyoMJmZZnM3J2CYqPGO1nKRaAO4FylUGDl2OdrNZ5M5uB58OHATMKd5l1d8et9tSOgRgDkW4bK-HG+3u8PW-E6iM7GPBr4Z4vBZIo7nJAXuYf9ufIygAfYL+nJAw2avjaUZRnuB5ZpuO4AZBt6XgB15ULB96Pqmz6Lm+Ugfvo36-nmAHocBoGZuBm4qKy9ZSAABgAaq+BYACTAOhMqUVGxFZlGy7jk2XYysufGulQyYAILqOo6aZj2JD9pGMYKHGm5er6-qBia5qWmMbFUAJjx0MwdAwEY-ARmMMAQEYFg-t+ACiLT8AAQn4ACSYwRioDJMiAoFSKJ6icQUapciQPJ8uQyqCpKADssryiAtAMEwzComqGoCEIyoOMOfhjg6NBjBSVDWAW4poOooT8YFlrBbyfBhSAkpIJKIqyrgIBiJIYWUHFipMCshh7AAAoMwZqiYiDKp89RGeoEjWElJbaH1axwAN4rMGg62LKYzAiotuzEPp4j4mq6TqEq4AvOULUykAA) and [async flems](https://flems.io/#0=N4IgzgxgTg9gNnEAuA2gBgDRoLoZAMwEs4BTMZFUAOwEMBbE5EAOgAsAXOxPCGK9kvyYAeOISoBrAASsoJfAF4AOiA7sADmCQB6bTSjtWAVygRSDKmGYBzQoaMAjZoRh6wYEuzDb18AJ6GgiTaJAAe9Oqk3vjmVhDuKlJycMrg7H5RrCSeKgB8SlQFwpBQhOrsUmCmqWqaOnoGxqbmgla29k4ubh5ePv6BVMFg7DRUACY0cHzBvnABWYMAtHR2ssR9cwMky6ulcIvDoxNTg8wAVmB5wtolZez5hVTF0HeV1Sq1Wrr69s0kFm1Vo5nK4aO5PN5ZvMgjcRuNJtMNtClvFIf0FttUQc4cdpudLiBctdbuUHkUxoQAG5SQhjVKwGDsK7aCmU3IgPAeUgQdguSxMNBINCLABsSAATABGEAAXww1HojCQLAuHJAvH4gnYTA1wykwCkABUwuwAGKEEhwMZSGVSBRSKFbADcBQKuoqAHkqABhVijawkY2hM0Wq12qQACgAlHbcvqClIpO7KiMBOHgAnE1IaOx2FAAGqTIwkJBSADkZYwmcTlKLJakKjAMAYUjG8hoRjgFQEwZUVaoiZlmczcnYJgHGYHWb40BIOfrlKoMDbsZT8+YObzhbgxfDi+XJA3uagVlrO5I-azUkpFoA7qX9yuFHHJ1fE4R8JHDgIj1u61IAEJ7UfQ9NxPZgz2LGNXzfRNv0PSCSD3Jc21-cDEJdKdYPgtDt13YCUNA49TzrTDYKHLCs2TRDwxwjDqyzUdxykOgIwrS9YJYtjKy4stxHUIx2B4g0+H4wTSyQ581x-Gj7UPEYoADdgILrDBr3-GUoyjDjYNY9jeLEoS1JEqhDIk1c6P-OTmAUpSVPPNSaM07SGKvViVFZPspAAAzw+sABJgEQmVvKjVypCjMiswowdMJlTC3T4PUAEF1HUcNo1XGDSAqME-AgIMKntCsop6Q1CAYGBBIjTKpIjBi8oKk1wxUQ1WEIMAaU6-BYDobMwD8KgID7Bi6GYOQxigGhb2jTNtKkEU0DQSLhynJioAnBibxIe9IxjKTWK9X1-UDE1zUtMZjPU89S0awqbTCqcKPi10qDGugqv4CMxhgCAjAsZSlIAURafgACE-AASTGeqQAZJkQHm1L1BWqg1S5EgeT5chlUFSUAHZZXlEBaAYJhmFRNUNQEIRlQcZc-HjKd1BoMYKSoaxS3FNB1FCOL0ctTHeSSphJSQSURVlXAQDESQccoEnFSYFZDD2AABQZgzVExEGVT56iMKh1AkawKebbQVbWOA1fFZg0DtxZTGYEULd2YhmBWKh8TVdJ1CVcAXnKKWZSAA)

**Comment by ArthurClemens** [comment]
Fixed in 1.7.0
