### ISSUE TITLE
TypeScript definitions requires "element" property on Button component to be string

### ISSUE THREAD

**Issue by andershol** [ArthurClemens/polythene#86]
While trying to follow the migration sample in the [release notes for 1.7](https://github.com/ArthurClemens/polythene/releases/tag/v.1.7.0), I found that it seems that the TypeScript definition for the Button component have not been updated to allow m.route.Link to be used for the element property.
(the samples use a "h" in place of a "m" in e.g. "h.route.Link", but I assume that there is no significance to that)

**Comment by ArthurClemens** [comment]
Thanks for reporting.

Fixed in `1.7.1`.

**Comment by andershol** [comment]
Thanks for fixing :)
