### ISSUE TITLE
Usage documentation doesn't match up with npm's distro

### ISSUE THREAD

**Issue by impinball** [ArthurClemens/Polythene#9]
In each of the examples, the `polythene/$COMPONENT` name doesn't match up with the version on npm. The only way to unbreak them is by changing each of them to `polythene/lib/$COMPONENT`. This came up on Mithril's Gitter room.

**Comment by impinball** [comment]
Note that I'm filing this issue on behalf of @sector119.

**Comment by ArthurClemens** [comment]
This was an issue with jspm, solved with SHA: 515c759a68a05aa3a1b56b86f76448f906b68052
