### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by kyleada** [ArthurClemens/polythene#90]
hi, thank you for your work. but I met these errors. why? please  

If the 'mithril' package actually exposes this module, consider sending a pull request to amend 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mithril`
../../node_modules/polythene-css/index.d.ts(2,51): error TS7016: Could not find a declaration file for module 'polythene-css-base-spinner'. '/Users/wangkai/perfetto/code/perfetto/node_modules/polythene-css-base-spinner/dist/polythene-css-base-spinner.js' implicitly has an 'any' type.
  Try `npm install @types/polythene-css-base-spinner` if it exists or add a new declaration (.d.ts) file containing `declare module 'polythene-css-base-spinner';`
../../node_modules/polythene-mithril-button-group/index.d.ts(1,27): error TS7016: Could not find a declaration file for module 'mithril'. '/Users/wangkai/perfetto/code/perfetto/node_modules/mithril/index.js' implicitly has an 'any' type.

**Comment by ArthurClemens** [comment]
Could you try https://github.com/ArthurClemens/polythene-mithril-typescript-setup ? Add a base spinner instead of a button to see if you get the same error.

**Comment by kyleada** [comment]
@ArthurClemens 
thank you. I worked well when I run the setup project.

Actually, I want to take polythene in another project of google open source to build our version. 
[https://github.com/google/perfetto/tree/master/ui](https://github.com/google/perfetto/tree/master/ui)

I copied and pasted "setup-projec"t  tsconfig.json, then it showed:

` Type '{ default: Static; route: Route; mount: { (element: Element, component: ComponentTypes<any, any>): void; (element: Element, component: null): void; }; ... 9 more ...; trust(html: string): Vnode<...>; }' has no call signatures.
../../ui/src/query/index.ts(304,40): error TS2349: This expression is not callable.
  Type '{ default: Static; route: Route; mount: { (element: Element, component: ComponentTypes<any, any>): void; (element: Element, component: null): void; }; ... 9 more ...; trust(html: string): Vnode<...>; }' has no call signatures.
`

thank you very much. I think I should learn more frontend program info

**Comment by ArthurClemens** [comment]
Perfetto uses Mithril version `1.1.7`. I suspect there's an incompatibility with the more recent typings that Polythene uses.

**Comment by ArthurClemens** [comment]
Version 1.7.3

**Comment by ArthurClemens** [comment]
I've added a definition for `RouteLinkAttrs` to support Mithril 1.x. Please let me know if it works now.

Version 1.7.4
