### ISSUE TITLE
Layout examples and max width

### ISSUE THREAD

**Issue by codechips** [ArthurClemens/polythene#96]
Hi! Thanks for a great and very extensive library! I am currently trying to learn it and all the component documentation is great. However, I can't find any documentation on how how set the width of the layouts and overall general "app shell" examples.  

My question: Is there a way to restrict the max-width of the layout based on the screen width? Is there a container class or something that I can use? The Polythene Way? Thinking of the desktop mode.

Any tips, pointers or examples would be much appreciated.

**Comment by ArthurClemens** [comment]
Hi @codechips, for support questions you can also reach me in the [Gitter channel](https://gitter.im/ArthurClemens/Polythene).

Polythene does not offer any wrappers or tooling for layout. You can just use a wrapper div and use CSS styles with media queries.

**Comment by codechips** [comment]
Got it. Thanks for a quick answer! Will use Gitter next time! Closing.
